#include <stdio.h>
#include <stdlib.h>

/*  DEFINITION: Frame
    A frame refers to a storage frame or central storage frame. In terms of
    physical memory, it is a fixed sized block in physical memory space, or
    a block of central storage. 

    The logical/virtual address generated by the CPU is stored in a set of
    blocks known as pages and the physical address generated by the memory
    is stored in frames. */

char globBuf[65536];                /*  Unintialized data segment */
int primes[] = {2, 3, 5, 7};        /*  Initialized data segment */

static int square(int x) {          /*  Allocated in frame for square() */
    int result;                     /*  Allocated in frame for square() */
    result = x * x;                 /*  Allocated in frame for square() */
    return result;
}

static void doCalc(int val) {       /*  Allocated in frame for doCalc() */
    printf("The square of %d is %d\n", val, square(val));
    if (val < 1000) {
        int t;                      /*  Allocated in frame for doCalc() */
        t = val * val * val;
        printf("The cube of %d is %d\n", val, t);
    }
}

int main(int argc, char *argv[]) {  /* Allocated in frame for main() */
    static int key = 9973;          /* Initialized data segment */
    static char abuf[10240000];     /* Unintialized data segment */
    char *p;                        /* Allocated in frame for main() */

    p = malloc(1024);               /* Points to memory in heap segment */
    doCalc(key);

    /* This causes a segmentation fault core-dumped */
    // int arrInt[10000000];
    // for (int i = 0; i < 10000000; ++i)
    //     arrInt[i] = i;

    int *arrIntP = malloc(10000000 * sizeof(int));
    for (int i = 0; i < 10000000; ++i) {
        arrIntP[i] = i;
        printf("%d ", arrIntP[i]);
    }
    free(arrIntP);
    exit(EXIT_SUCCESS);
}

/*  NOTE: Difference between array type [] and array allocated (malloc)
    Automatic storage duration. The array lives only as long as the function
    that calls it exists. Example: int array[1024]; 
    Dynamic storage duration. It will exist until it is explicitly deallocated
    with free. Example: int* array = malloc(1024 * sizeof(int));

    C memory is split into several regions, including the stack (functions calls
    and local variables) and the heap (for malloc ed objects). The stack
    tipically has a much smaller size than the heap. 

    Variable-length arrays in C can easily exceed the stack size. Prefer malloc
    unless it is guaranteed that the size of the array is small. */
